version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "crieti"
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

  node:
    image: node:18
    volumes:
    - ./app/:/home/node/app

networks: 
  postgres-compose-network:
    driver: bridge